name: Build Images

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: skorionos/skorion-bootc

jobs:
  build-minimal:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build minimal image
        run: |
          docker build -f Containerfile.minimal \
            -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:minimal-latest \
            -t skorionos:minimal-latest \
            .
      
      - name: Push minimal image
        if: github.event_name != 'pull_request'
        run: docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:minimal-latest

  build-base:
    needs: build-minimal
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Pull minimal image
        run: docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:minimal-latest
      
      - name: Tag minimal as skorionos:minimal-latest
        run: docker tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:minimal-latest skorionos:minimal-latest
      
      - name: Build base image
        run: |
          docker build -f Containerfile.base \
            -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:base-latest \
            -t skorionos:base-latest \
            .
      
      - name: Push base image
        if: github.event_name != 'pull_request'
        run: docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:base-latest

  build-variants:
    needs: build-base
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        variant: [kde, gnome, hyprland]
    steps:
      - uses: actions/checkout@v4
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Pull base image
        run: docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:base-latest
      
      - name: Tag base as skorionos:base-latest
        run: docker tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:base-latest skorionos:base-latest
      
      - name: Build ${{ matrix.variant }} image
        run: |
          docker build -f Containerfile.${{ matrix.variant }} \
            -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ matrix.variant }}-latest \
            .
      
      - name: Push ${{ matrix.variant }} image
        if: github.event_name != 'pull_request'
        run: docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ matrix.variant }}-latest
